sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pibJqVPsz+QRzKK4gMDYZCNjwDx+IfcLuavapkKpsxpT5yTxpCrvEcZ2d1NZE+G0b/3nkad38P8Jw3zxk4jtI8amEv7cNJsgy7FqoI1CxqqvyMFuW9Is0yJiB1DgVojuu5RnH2kkLkSm7ierlkd6KCQVdUJShXSKXLp6Br2O/Hr452UFadFLqqfsKEMzQ12SNw4xSheqJNiktiymqvw+VLXoNOyr6oTL3lu8YqUcNO4apGicjdMl6KRqUCTaVtlUKQX4lOQb7S+4OfObq3Z8ogu3HfKP59CaK3Q6dsQOmWTcPe67ueZEWjkDQ+Bj9NgSyTYOkJfSkjY2WlAIMg0wIjUCw6JlGeuLDJvfJfS2406NFvMoETOMAwdZHMmxsQcXt/GeNaDDud44+KGWTH17n2lFfsncJ9ohFj1XhM7lLBKW85irFeCYkyF0zw4tSXedDnPDqezvRfBBY7usrYITSskyiTF+u0cM2Gi5cIeAkqxyTvslq6yjMgId0dwOUa9OlYDzUe4yQRvDAwQjCFYAu4u5y+xu4L5MCsIVmzjKa1g6HyM2SMfEIzxIvbSfddubdvtrsZvKdJJd26M432Fqgm16QKt/M6rC/on2uVTiVX8QqpJssH2QFo8zEaiIm9aJ56N9aPqb46F8IxZFlLYRsszSlU3Bl+JIcAQ4gT1mzeg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Original-Short-Stories---Volume-13_3089
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy